name: goreleaser-latest

on:
  push:
    branches:
      - main
      - mainnet-664
      - develop

permissions:
  contents: write
  packages: write

jobs:
  goreleaser-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Release (snapshot)
        run: make release-snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to GHCR container register
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push versioned image
      #   uses: docker/build-push-action@v5
      #   with:
      #     file: contrib/docker/goreleaser.Dockerfile
      #     context: .
      #     push: true
      #     platforms: linux/amd64,linux/arm64
      #     tags: ghcr.io/composablefi/composable-cosmos:latest
